### ISSUE TITLE
Löschen-Funktion

### ISSUE THREAD

**Issue by newcat** [newcat/Showroom2#20]
Der Löschen-Knopf für ein Projekt im Admin-Modus hat noch keine Funktion.

## WICHTIG
Vor dem Löschen sollte noch ein Popup kommen, mit der Frage, ob das Projekt wirklich gelöscht werden soll. Das Projekt kann anschließend mittels der `deleteCode` Methode im `dataloading.XmlDataManager` gelöscht werden (https://github.com/newcat/Showroom2/blob/master/app/src/main/java/dataloading/XmlDataManager.java#L32)

**Comment by newcat** [comment]
Ist praktisch fertig (danke @Jonathan997 ) - Bug im XmlDataManager wird bereits gefixed

**Comment by lessing-dev** [comment]
Läuft wie am Schnürchen
